// Code generated by protoc-gen-go.
// source: pkg1/pkg11/bar.proto
// DO NOT EDIT!

/*
Package pkg11 is a generated protocol buffer package.

It is generated from these files:
	pkg1/pkg11/bar.proto
	pkg1/pkg11/bar1.proto

It has these top-level messages:
	Bar
	Bar1
*/
package pkg11

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Bar struct {
}

func (m *Bar) Reset()                    { *m = Bar{} }
func (m *Bar) String() string            { return proto.CompactTextString(m) }
func (*Bar) ProtoMessage()               {}
func (*Bar) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func init() {
	proto.RegisterType((*Bar)(nil), "pkg1.pkg11.Bar")
}

func init() { proto.RegisterFile("pkg1/pkg11/bar.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 88 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0x12, 0x29, 0xc8, 0x4e, 0x37,
	0xd4, 0x07, 0x11, 0x86, 0xfa, 0x49, 0x89, 0x45, 0x7a, 0x05, 0x45, 0xf9, 0x25, 0xf9, 0x42, 0x5c,
	0x20, 0x01, 0x3d, 0xb0, 0xa8, 0x12, 0x2b, 0x17, 0xb3, 0x53, 0x62, 0x91, 0x93, 0x42, 0x94, 0x5c,
	0x46, 0x6a, 0x4e, 0x4e, 0x7e, 0x79, 0x7e, 0x51, 0x4e, 0x8a, 0x7e, 0x41, 0x52, 0x7c, 0x49, 0x51,
	0x66, 0x62, 0x8e, 0x3e, 0x42, 0x7b, 0x12, 0x1b, 0x58, 0xaf, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff,
	0x2d, 0x61, 0x2e, 0x4f, 0x53, 0x00, 0x00, 0x00,
}
